phases:

- phase: Build_And_Package_Linux
  #queue: Hosted Linux Preview (Hosted Linux Preview)
  steps:
  - script: echo hello from Linux
  
  - bash: |
      echo current dir is $PWD
      ls
    workingDirectory: $(system.defaultWorkingDirectory)
    displayName: Print Working directory
    
  - bash: |
      dotnet restore src,
      dotnet build src
      dotnet test src/Sample.Tests
      dotnet publish src/Sample.Web.Api/Sample.Web.Api.csproj -c Release -f netcoreapp2.0
    displayName: Build, Test, Publish
    workingDirectory: $(system.defaultWorkingDirectory)
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      
  - bash: |
      cp src/Dockerfile src/Sample.Web.Api/bin/Release/netcoreapp2.0/publish/
      docker build --rm --no-cache -t $DOCKER_IMAGE_NAME_WITH_REGISTRY src/Sample.Web.Api/bin/Release/netcoreapp2.0/publish/
      docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME -p $DOCKER_REGISTRY_SERVER_PASSWORD
      docker push $DOCKER_IMAGE_NAME_WITH_REGISTRY
    displayName: Push Docker Image
    workingDirectory: $(agent.homeDirectory)

#- phase: Deploy_Windows
#  queue: Hosted VS2017 (Hosted VS2017)
#  steps:
#  - script: az --version
