steps:

- bash: echo current dir is $PWD and agent homeDir is $(agent.homeDirectory) and default dir is $(system.defaultWorkingDirectory)
  displayName: Working directory
  
- bash: |
    dotnet restore src
    dotnet build src
    dotnet test src/Sample.Tests
    dotnet publish src/Sample.Web.Api/Sample.Web.Api.csproj -c Release -f netcoreapp2.0
  displayName: Build, Test, Publish
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1