apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: container-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
        - name: container-api
          image: pinkteam.azurecr.io/samplewebapp
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: aksregistry
---
apiVersion: v1
kind: Service
metadata:
  name: container-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: container-api-app