apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-web-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
        - name: sample-web-container
          image: pinkteam.azurecr.io/samplewebapp
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: sample-web-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sample-web-app